/*
   Page de login OTA
*/
const char* loginOTA =
  "<form name='loginForm' id='loginForm' method='POST' action='serverota'>\n"
  "<table width='20%' bgcolor='A09F9F' align='center'>\n"
  "<tr>"
  "<td colspan=2>"
  "<center><font size=4><b>Page de connexion pour mise &agrave; jour</b></font></center><br/>"
  "</td>"
  "</tr>\n"
  "<tr>"
  "<td>Utilisateur:</td>"
  "<td><input type='text' size=25 name='userid'/><br></td>"
  "</tr>\n"
  "<tr>"
  "<td>Mot de passe:</td>"
  "<td><input type='Password' size=25 name='pwd'/><br></td>"
  "</tr>\n"
  "<tr>"
  "<td align='center' colspan=2><input type='submit' onclick='check(this.form);' value='Connexion'/></td>"
  "</tr>\n"
  "<tr>"
  "<td align='center' colspan=2><input type='button' onclick='history.back();' value='Annuler'/></td>"
  "</tr>\n"
  "</table>\n"
  "</form>\n"
  "<script type=\"text/javascript\">\n"
  "function check(form) {\n"
  "  if(form.userid.value != '' && form.pwd.value != '') {\n"
  "    document.getElementById('loginForm').submit();\n"
  "  } else {\n"
  "    alert(\"Erreur: Mot de passe et nom d'utilisateur obligatoire.\");\n"
  "  }\n"
  "}\n"
  "</script>\n";

/*
   Server de mise à jour OTA
*/
const char* serverOTA =
  "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>\n"
  "<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>\n"
  "<input type='file' name='update'/>&nbsp;&nbsp;<input type='submit' value='Update'/>"
  "</form>\n"
  "<div id='prg'>progression: 0%</div><br/>\n"
  "<div id='prg'><input type='button' value='Annuler' onClick=\"document.location.href='/param.htm';\"/></div>\n"
  "<script type=\"text/javascript\">\n"
  "$('form').submit(function(e) {\n"
  "  e.preventDefault();\n"
  "  var form = $('#upload_form')[0];\n"
  "  var data = new FormData(form);\n"
  "  $.ajax({\n"
  "    url: '/update', type: 'POST', data: data, contentType: false, processData:false,\n"
  "    xhr: function() {\n"
  "      var xhr = new window.XMLHttpRequest();\n"
  "      xhr.upload.addEventListener('progress', function(evt) {\n"
  "        if (evt.lengthComputable) {\n"
  "          var per = evt.loaded / evt.total;\n"
  "          $('#prg').html('progression: ' + Math.round(per*100) + '%');\n"
  "        }\n"
  "      }, false);\n"
  "      return xhr;\n"
  "    },\n"
  "      success:function(d, s) {\n"
  "        console.log('r&egrave;ussie !')"
  "      },\n"
  "      error: function (a, b, c) {\n"
  "      }\n"
  "    });\n"
  "  });\n"
  "</script>\n";
